read config from config.ini

diff --git a/ROOTFS/usr/bin/sagebk-reverse-tunnel b/ROOTFS/usr/bin/sagebk-reverse-tunnel
--- a/ROOTFS/usr/bin/sagebk-reverse-tunnel
+++ b/ROOTFS/usr/bin/sagebk-reverse-tunnel
@@ -1,7 +1,34 @@
-#!/bin/bash
+#!/bin/bash -e
 
-HOST=beekeeper
+CONFIG_FILE=/etc/waggle/config.ini
 key_file=/etc/waggle/key.pem
+
+
 id=$(</etc/waggle/node-id)
 
-ssh -vv -N  -R /home_dirs/$id/rtun.sock:localhost:22 $id@beekeeper -p 20022 -i /etc/waggle/key.pem
+
+if [ "${id}_" == "_" ] ; then
+    echo "Error: Node id missing"
+    exit 1
+fi
+
+
+if [ ! -e ${CONFIG_FILE} ] ; then
+    echo "Error: Config file ${CONFIG_FILE} missing"
+    exit 1
+fi
+
+CONFIG_SECTION=$(grep '^\[registration\]' -A 999 ${CONFIG_FILE} | tail -n +2  | grep -B 999 '^\[' | head -n -1)
+
+BK_HOST=$(echo ${CONFIG_SECTION} | tr ' ' '\n' | grep host | cut -d '=' -f 2)
+echo "BK_HOST=${BK_HOST}"
+
+BK_PORT=$(echo ${CONFIG_SECTION} | tr ' ' '\n' | grep port | cut -d '=' -f 2)
+echo "BK_PORT=${BK_PORT}"
+
+# source: https://stackoverflow.com/a/64993893/2069181
+
+
+set -x
+
+ssh -vv -N  -R /home_dirs/$id/rtun.sock:localhost:22 $id@${BK_HOST} -p ${BK_PORT} -i /etc/waggle/key.pem
